### ISSUE TITLE
The /logout page still logs out the recent logged in device.

### ISSUE THREAD

**Issue by brodante** [brodante/SignOutSync#10]
The /logout page logs out the recent logged in device, whereas it should logout the device that matches the device_id.

**Comment by RudrasSingh** [comment]
Hi @brodante !
wanna work on this issue, I have a solution in mind.
Kindly add the hacktoberfest label as well!

Thanks!

**Comment by brodante** [comment]
sup @RudrasSingh !
I will assign this issue to you and also add the hacktoberfest label to it!
Cheers!

**Comment by RudrasSingh** [comment]
@brodante fixed the issue and made some more changes.
Kindly check and merge!
thanks

**Comment by brodante** [comment]
@RudrasSingh, I tested the code and found an issue. Here are the steps to replicate it, so you can check it at your convenience:

1. **Log in** from multiple devices (using different user-agent headers).
2. Navigate to **/devices** to see the list of active devices; you should see the total number of devices you’ve logged in from.
3. Go to **/logout** and select any device to log out from. For example, if I’m logged in from 4 devices, I log out from the second one in order.
4. Check **/devices** again. You’ll notice only the device you intended to log out from remains listed, while the others are logged out unexpectedly.

I've attached an image for reference. Let me know if you need further details!
![image](https://github.com/user-attachments/assets/71dda3b3-a1fa-4b18-af9e-7c810e07e5c1)
_Here you can see that there a 4 devices currently logged in_

<hr>

![image](https://github.com/user-attachments/assets/a4ba6835-f8fa-4107-92d2-a0ec24e62646)
_and here you can see after a single logout request it logs out all other devices except the one the signal is meant for_

**Comment by RudrasSingh** [comment]
@brodante I got it what you saying, but the issue says that the user's devices should be logged out except the most recent one logged in! And it's exactly doing that using the ```username``` attribute.

If that's not the point so what exactly it should do? Only log out those devices whose ```device_id``` matches?

**Comment by brodante** [comment]
Yes @RudrasSingh  you got that right!

> The /logout page logs out the recent logged in device, whereas it should logout the device that matches the device_id.

It states that, the request to /logout just logs out the last device logged in, whereas it should logout the device whose, data, i.e. device_id, matches the one logged in, if not present it should say that device is not logged in, else it should logout the device. I apologise if there was some misunderstanding in the wordings. feel free to ask if you need to know anything!

**Comment by RudrasSingh** [comment]
Okay @brodante ...
What I will do is, instead of choosing on the basis of ```username``` I will choose on the basis of ```device_id``` which will be taken from the request.
Then will make only that device logout for the user which is selected not the complete one.
Which will be done by parsing the database for active devices. 
Is that right?

**Comment by brodante** [comment]
> Okay @brodante ... What I will do is, instead of choosing on the basis of `username` I will choose on the basis of `device_id` which will be taken from the request. Then will make only that device logout for the user which is selected not the complete one. Which will be done by parsing the database for active devices. Is that right?

Yes @RudrasSingh you're on the right track!
Keep up the good work!

 _Your efforts will be rewarded someday. 
 ~Yu Ishigami_

**Comment by RudrasSingh** [comment]
sup @brodante!?
Updated the code as per your requirement.
Check and merge!
attaching the images as well for reference:
![image](https://github.com/user-attachments/assets/cba987c7-606e-4cdf-a78d-95b8e84de5a9)
![image](https://github.com/user-attachments/assets/bfa6b22d-df5f-406a-bfea-dd209f9518a4)
![image](https://github.com/user-attachments/assets/56e796ba-5346-4193-9d16-c863541c8f31)

**Comment by brodante** [comment]
@RudrasSingh Good Work!!
I will merge the branch and mark this issue as completed.
keep it up.
